# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'insta-clone-firebase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'SDWebImage'
pod 'OneSignal', '>= 2.11.2', '< 3.0'

target 'OneSignalNotificationServiceExtension' do
  #only copy below line
  pod 'OneSignal', '>= 2.11.2', '< 3.0'
end

  # Pods for insta-clone-firebase

end
