# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'snapchat-clone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for snapchat-clone
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Firestore'
pod 'Firebase/Core'
pod 'SDWebImage'
pod 'ImageSlideshow'
pod 'ImageSlideshow/Kingfisher'

end
